disabled_rules: # rule identifiers to exclude from running
  # - colon
  # - comma
  # - control_statement
  - trailing_whitespace
  - missing_docs
  - line_length 
  - variable_name
  - nesting
opt_in_rules: # some rules are only opt-in
  - empty_count
  # Find all the available rules by running:
  # swiftlint rules

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
# they can set both implicitly with an array
type_body_length:
  - 600 # warning
  - 900 # error
# or they can set both explicitly
file_length:
  warning: 1000
  error: 1500
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
function_body_length:
  warning: 100  
  error: 150
type_name:
  min_length: 1 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
variable_name:
  min_length: # only min_length
    error: 0 # only error
  excluded: # excluded via string array
    # - id
    # - URL
    # - GlobalAPIKey
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit)
